// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import mdx from '@astrojs/mdx';

// https://astro.build/config
export default defineConfig({
  site: 'https://diegocasmo.github.io',
  integrations: [sitemap(), mdx()],
  markdown: {
    shikiConfig: {
      theme: 'tokyo-night',
      langs: [],
      wrap: true,
    },
  },
  redirects: {
    '/2015-05-27-simple-bdd-backbone-views/': '/simple-bdd-backbone-views/',
    '/2015-07-28-backbone-required-attributes/': '/backbone-required-attributes/',
    '/2015-12-17-karatsuba-multiplication/': '/karatsuba-multiplication/',
    '/2015-12-20-merge-sort/': '/merge-sort/',
    '/2015-12-26-fft/': '/fft/',
    '/2016-01-01-depth-first-search-undirected-graphs/': '/depth-first-search-undirected-graphs/',
    '/2016-01-18-getting-started-with-acceptance-testing/': '/getting-started-with-acceptance-testing/',
    '/2016-01-28-better-performance-on-the-client/': '/better-performance-on-the-client/',
    '/2016-03-07-an-introduction-to-data-mining/': '/an-introduction-to-data-mining/',
    '/2016-08-01-the-basics-of-typescript/': '/the-basics-of-typescript/',
    '/2016-08-22-virtual-box-ssh-shared-folders-tutorial/': '/virtual-box-ssh-shared-folders-tutorial/',
    '/2016-10-24-passing-variables-in-an-isomorphic-application/': '/passing-variables-in-an-isomorphic-application/',
    '/2017-01-23-navigation-redirects-through-redux-middleware/': '/navigation-redirects-through-redux-middleware/',
    '/2017-02-06-a-simple-react-tabs-component/': '/a-simple-react-tabs-component/',
    '/2017-07-10-a-short-list-of-good-practices-in-programming/': '/a-short-list-of-good-practices-in-programming/',
    '/2018-10-24-convolutional-neural-networks-for-galaxy-morphology-classification/': '/convolutional-neural-networks-for-galaxy-morphology-classification/',
    '/2018-11-09-iam-dataset-writer-recognition-using-a-cnn/': '/iam-dataset-writer-recognition-using-a-cnn/',
    '/2019-08-11-okrs-as-a-framework-for-personal-growth/': '/okrs-as-a-framework-for-personal-growth/',
    '/2019-08-12-using-active-support-concerns-to-encapsulate-data-access-and-validation/': '/using-active-support-concerns-to-encapsulate-data-access-and-validation/',
    '/2019-08-19-using-postgres-enum-type-in-rails/': '/using-postgres-enum-type-in-rails/',
    '/2020-10-18-create-a-simple-react-timer-component/': '/create-a-simple-react-timer-component/',
    '/2021-08-29-email-and-password-based-authentication-with-expo-and-firebase-part-1-project-setup/': '/email-and-password-based-authentication-with-expo-and-firebase-part-1-project-setup/',
    '/2021-09-10-email-and-password-based-authentication-with-expo-and-firebase-part-2-sign-up-email-verification-and-sign-out/': '/email-and-password-based-authentication-with-expo-and-firebase-part-2-sign-up-email-verification-and-sign-out/',
    '/2021-09-19-email-and-password-based-authentication-with-expo-and-firebase-part-3-sign-in-forgot-password-and-update-password/': '/email-and-password-based-authentication-with-expo-and-firebase-part-3-sign-in-forgot-password-and-update-password/',
    '/2022-12-19-api-using-axios-react-query/': '/api-using-axios-react-query/',
    '/2024-10-06-our-most-valuable-asset/': '/our-most-valuable-asset/',
    '/2024-10-07-simple-next.js-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/': '/simple-nextjs-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/',
    '/simple-next.js-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/': '/simple-nextjs-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/',
    '/2025-08-05-reducing-type-overhead-with-lazy-evaluation-in-typescript/': '/reducing-type-overhead-with-lazy-evaluation-in-typescript/',
    '/2025-08-25-intent-first-software/': '/intent-first-software/',
    '/2025-12-01-onboarding-as-an-engineer-in-the-age-of-ai/': '/onboarding-as-an-engineer-in-the-age-of-ai/',
    // Redirect /posts/{slug}/ to /{slug}/ (legacy paths)
    '/posts/a-short-list-of-good-practices-in-programming/': '/a-short-list-of-good-practices-in-programming/',
    '/posts/a-simple-react-tabs-component/': '/a-simple-react-tabs-component/',
    '/posts/an-introduction-to-data-mining/': '/an-introduction-to-data-mining/',
    '/posts/api-using-axios-react-query/': '/api-using-axios-react-query/',
    '/posts/backbone-required-attributes/': '/backbone-required-attributes/',
    '/posts/better-performance-on-the-client/': '/better-performance-on-the-client/',
    '/posts/convolutional-neural-networks-for-galaxy-morphology-classification/': '/convolutional-neural-networks-for-galaxy-morphology-classification/',
    '/posts/create-a-simple-react-timer-component/': '/create-a-simple-react-timer-component/',
    '/posts/depth-first-search-undirected-graphs/': '/depth-first-search-undirected-graphs/',
    '/posts/email-and-password-based-authentication-with-expo-and-firebase-part-1-project-setup/': '/email-and-password-based-authentication-with-expo-and-firebase-part-1-project-setup/',
    '/posts/email-and-password-based-authentication-with-expo-and-firebase-part-2-sign-up-email-verification-and-sign-out/': '/email-and-password-based-authentication-with-expo-and-firebase-part-2-sign-up-email-verification-and-sign-out/',
    '/posts/email-and-password-based-authentication-with-expo-and-firebase-part-3-sign-in-forgot-password-and-update-password/': '/email-and-password-based-authentication-with-expo-and-firebase-part-3-sign-in-forgot-password-and-update-password/',
    '/posts/fft/': '/fft/',
    '/posts/getting-started-with-acceptance-testing/': '/getting-started-with-acceptance-testing/',
    '/posts/iam-dataset-writer-recognition-using-a-cnn/': '/iam-dataset-writer-recognition-using-a-cnn/',
    '/posts/intent-first-software/': '/intent-first-software/',
    '/posts/karatsuba-multiplication/': '/karatsuba-multiplication/',
    '/posts/merge-sort/': '/merge-sort/',
    '/posts/navigation-redirects-through-redux-middleware/': '/navigation-redirects-through-redux-middleware/',
    '/posts/okrs-as-a-framework-for-personal-growth/': '/okrs-as-a-framework-for-personal-growth/',
    '/posts/onboarding-as-an-engineer-in-the-age-of-ai/': '/onboarding-as-an-engineer-in-the-age-of-ai/',
    '/posts/our-most-valuable-asset/': '/our-most-valuable-asset/',
    '/posts/passing-variables-in-an-isomorphic-application/': '/passing-variables-in-an-isomorphic-application/',
    '/posts/reducing-type-overhead-with-lazy-evaluation-in-typescript/': '/reducing-type-overhead-with-lazy-evaluation-in-typescript/',
    '/posts/simple-bdd-backbone-views/': '/simple-bdd-backbone-views/',
    '/posts/simple-nextjs-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/': '/simple-nextjs-magic-link-jwt-authentication-with-prisma-postgresql-and-resend/',
    '/posts/the-basics-of-typescript/': '/the-basics-of-typescript/',
    '/posts/using-active-support-concerns-to-encapsulate-data-access-and-validation/': '/using-active-support-concerns-to-encapsulate-data-access-and-validation/',
    '/posts/using-postgres-enum-type-in-rails/': '/using-postgres-enum-type-in-rails/',
    '/posts/virtual-box-ssh-shared-folders-tutorial/': '/virtual-box-ssh-shared-folders-tutorial/',
  },
});
